module.exports = require("yargs")
    .usage(
        "Webant: the intelligent javascript web bundler - (c) 2013 A Kazim\n\n" +
        "Usage:\n" +
        "  webant --useConfig [options]\n" + 
        "  webant --useConfig [path to config file] [options]\n" +
        "  webant --entry [path to entry script] [options]\n\n" +
        "Example:\n" +
        "  webant --entry src/js/main.js --dest build/js/main.js"
    )
    .describe("entry","Path to entry script relative to current directory. [Required, unless --useConfig flag is set].")
    .describe("dest","Path to where compiled output will be written.")
    .describe("urlDest","URL at which the path specified for '--dest' can be reached. Can be absolute or relative. Example: --urlDest js/main.js")
    .describe("postProcess","Post-processing to apply to compiled javascript. Can be either 'compress' (compresses output), 'debug' (adds file and line numbers to output) or 'none' (no post-processing).")
    .describe("requireBase","Resolve require paths relative to the supplied directory instead of relative to the file containing the require.")
    .describe("defaultExtension","Default extension to append to a require path when no extension is provided. Include the starting period (e.g. '.ts'). Example: setting `--defaultExtension .coffee` would mean that `require('./path/to/file')` would look for `./path/to/file.coffee`. Defaults to '.js'.")
    .describe("handlers","Additional handlers to use. Can be set multiple times. Example: -H coffee -H scss -H json")
    .describe("includeBootstrap","The path to the file where the bootstrap code will be included. This should be set to one of the source files to be compiled. Webant will then insert the bootstrap code into the compiled version of the specified source file. Alternatively set this to the empty string for no bootstrap code to be included. Leave undefined for the bootstrap code to be included in the entry file specified via the `--entry` key.")
    .describe("browserGlobalVar","Name of the global variable used in the compiled javascript. Defaults to '__MODULES__'.")
    .describe("aliases","Parameters that can be used as part of `require` calls. Example: passing `--aliases.foo=jquery --aliases.baz=lib` would mean you could do `require('../{baz}/{foo}.js')` in your scripts.")
    .describe("entryModules","Path to entry modules. These are the modules that are automatically loaded when the compiled javascript is included in a webpage. This can be set multiple times. Leave blank to default to the entry script passed via the --entry key. Example usage: -E path/to/src/1.js -E path/to/src/2.js")
    .describe("requireExpressionName","Name of the function used for requiring javascript files. Defaults to 'require'.")
    .describe("useConfig","Path to a JSON configuration file which sets default options. If this option is set but no path is provided, the path is assumed to be './webant-config.json'. [Required, unless --entry option is provided]. [Additional options override those found in the configuration file].")
    .describe("version","Show version.")
    .describe("help","Show help.")
    .alias("entry","e")
    .alias("dest","d")
    .alias("urlDest","u")
    .alias("postProcess","p")
    .alias("requireBase","r")
    .alias("defaultExtension","D")
    .alias("handlers","H")
    .alias("includeBootstrap","i")
    .alias("browserGlobalVar","b")
    .alias("entryModules","E")
    .alias("requireExpressionName","R")
    .alias("useConfig","c")
    .alias("version","v")
    .alias("help","h")
    .string("entry")
    .string("dest")
    .string("urlDest")
    .string("postProcess")
    .string("includeBootstrap")
    .string("browserGlobalVar")
    .string("requireExpressionName")
    .string("useConfig")
    .boolean("version")
    .boolean("help")
    .wrap(80);